Add: bj 10026, programmers 42890
TheCopiens/algorithm-study pull request #44
Opened 2020-07-19 06:22 UTC by sypark9646

2020-07-21 15:17 UTC, OHHAKO requested changes
@sypark9646  님 7월 3주차를 유일하게 푸셨어요!
항상 좋은 풀이에 감사드려요:) 코드리뷰를 달았으니 답변 해주세요.

2020-07-21 15:17 UTC, OHHAKO commented on source/soyeon/[boj] 10026.md
> +	   color1[x][y]=0;
경로 중복을 피하기 위해 visited배열을 써야겠다고 생각했는데 지나온 길은 아예 0으로 표시했네요. 
제가 DFS를 많이 안써봐서 그러는데 흔히 쓰이는 방식인가요?

2020-07-21 15:17 UTC, OHHAKO commented on source/soyeon/[boj] 10026.md
> +   public static void findcolor2(int x,int y,int k){
배열 입력받을때 색약의 경우 G를 R취급 했으니 color2 배열 탐색시에 findcolor1 메서드를 썼어도 결과가 같지 않나요?

2020-07-21 15:17 UTC, OHHAKO commented on source/soyeon/[programmers] 42890.md
> +class Solution {
알고리즘 순서에 따른 각 메서드의 기능을 간략하게 설명 부탁드려요.

2020-07-21 15:32 UTC, sypark9646 commented on source/soyeon/[boj] 10026.md
> +	   color1[x][y]=0;
앗 일반적으로 BFS나 DFS 문제에서는 배열 안에 숫자가 연속된 수라서 visited 배열을 따로 쓰는 것 같아요. 그런데 이 문제에서는 배열을 또 만들기 귀찮기도 하고 color 배열에 색깔이 무조건 1,2,3 세가지밖에 없어서 0으로 표시해도 괜찮을 것 같다고 저는 생각해서 이렇게 풀었어요!

2020-07-21 15:35 UTC, sypark9646 commented on source/soyeon/[boj] 10026.md
> +   public static void findcolor2(int x,int y,int k){
넵넵 결국 같은 함수라서 findcolor 함수 하나로 줄이도록 하겠습니다!! 감사해요

2020-07-21 15:38 UTC, sypark9646 commented on source/soyeon/[programmers] 42890.md
> +	public boolean checkCandidateKey(HashSet<Integer> keySet, String[][] relation) {
후보 키가 될 수 있는지 확인하는 함수입니다.
후보 키를 이용해서 튜플이 식별되는지 확인하기 위해 HashSet에 후보키를 이용한 튜플 문자열을 넣습니다.
그 다음 HashSet에 이미 존재하는 튜플 문자열이 존재하는 경우 후보키가 될 수 없으므로 false를 리턴하고,
튜플이 모두 식별되는 경우 true를 리턴합니다.

2020-07-21 15:42 UTC, sypark9646 commented on source/soyeon/[programmers] 42890.md
> +	public static boolean containsAll(HashSet<Integer> big, HashSet<Integer> small) {
이 함수는 argument로 들어오는 big과 small hashset 중에 small이 big에 포함되는지 확인하는 함수입니다.
그런데 찾아보니까 https://www.geeksforgeeks.org/hashset-containsall-method-in-java-with-example/
hashSet이 다른 hashSet에 포함되는지 확인하는 함수가 있네요...! 이 함수는 필요 없고 위 함수를 사용하도록 하면 될 것 같아요

2020-07-21 15:44 UTC, sypark9646 commented on source/soyeon/[programmers] 42890.md
> +	public void createCandidateKey(int index, HashSet<Integer> keySet, String[][] relation) {
이 함수는 브루트포스로 모든 후보키의 조합을 만들고,
다 만들었을 경우 후보키인지 먼저 확인한 뒤, 전역 변수로 선언된 후보키 셋에 해당 조합을 넣는 함수입니다.

2020-07-21 15:46 UTC, sypark9646 commented on source/soyeon/[programmers] 42890.md
> +					HashSet<Integer> savedSet=candidateKeys.get(i);
만약 브루트 포스로 만들어진 keySet이 이미 저장된 후보키 집합 savedSet에 포함되는지 아닌지 확인하고,
만약 포함된다면 둘 중 더 작은 크기의 셋을 저장하도록 하는 부분입니다.

2020-07-26 08:00 UTC, OHHAKO commented on source/soyeon/[programmers] 42890.md
> +	public void createCandidateKey(int index, HashSet<Integer> keySet, String[][] relation) {
아 시간복잡도가 작아 모든 후보키의 조합을 만드셨군요.

2020-07-26 08:03 UTC, OHHAKO commented
코드리뷰가 완료되었습니다:)
원래 수정된 코드까지 추가 pr을 보내야 하는데 시간관계상^^; 변경된 코드는 추후 반영해주세요! 고생하셨어요.

2020-07-26 08:03 UTC, merged